### ISSUE TITLE
Please add support for Swift Package Manager (Dependencies)

### ISSUE THREAD

**Issue by ethanwa** [podkovyrin/APNumberPad#25]
Many people will be moving away from CocoaPods and Carthage and using Swift Package Manager (Dependencies). Can you please add support? Thank you!

**Comment by podkovyrin** [comment]
I've just added basic SwiftPM support in #26 but it has one limitation: since SwiftPM doesn't support resources or bundles so far and APNumberPad comes with default backspace icon.
Nevertheless, it can be used with custom `styleClass` proper set (on `APNumberPad` instance) which would refer backspace icon from user's resources.

I guess it can be worked around by drawing that icon as a shape via code, I'll consider the next steps in the new version of APNumberPad which is coming soon.

**Comment by ethanwa** [comment]
Xcode 12 and Swift 5.3 (both available as dev betas) now include resource and closed-source binary support for SPM. Hopefully SPM can now be done for this?

https://www.hackingwithswift.com/articles/218/whats-new-in-swift-5-3

**Comment by podkovyrin** [comment]
Sure, thanks for the link. I need some time to catch up with the new features.

**Comment by ethanwa** [comment]
Xcode 12 is now out as of today, just for an update on this.

**Comment by podkovyrin** [comment]
As an update: I made Swift PM work fine but there was an issue with CocoaPods. Hopefully, I'll solve it within a few days.

**Comment by podkovyrin** [comment]
Swift PM support branch has been merged, if you have any issue please let me know.

**Comment by ethanwa** [comment]
Awesome thank you! So far SPM support seems to be working great.

**Comment by podkovyrin** [comment]
I'll close the issue then. Feel free to post any issues you have.
